Settings:
  IP-Check: true
  CommandAliases: [code, giftcode]

Message:
  NoPermissions:
    text: "&cBạn không có quyền!"
    chat: true
    actionbar: false
  CodeReceived:
    text: "&aNhận quà thành công!"
    chat: true
    actionbar: false
  CodeNotExist:
    text: "&cMã không tồn tại!"
    chat: true
    actionbar: false
  AlreadyUsed:
    text: "&eBạn đã dùng mã này rồi!"
    chat: true
    actionbar: false
  IPLimit:
    text: "&cIP của bạn đã nhận mã này rồi!"
    chat: true
    actionbar: false

Help:
  - "&e&lARISCODE SYSTEM"
  - "&f/code <mã>"
  - "&f/code create <tên>"
  - "&f/code reload"
