name: ArisCode
version: 1.0
main: vennlmao.ariscode.Main
api-version: 1.20
author: VennLMAO
folia-supported: true
commands:
  code:
    description: Nhập giftcode
  ariscode:
    description: Quản lý giftcode
    permission: ariscode.admin
